### ISSUE TITLE
Stopped screen not shown anymore

### ISSUE THREAD

**Issue by darosior** [lvaccaro/lamp#43]
The screen of the turned off lamp does not show anymore when i stop Lamp (current master). It gets frozen on the last active screen.

**Comment by vincenzopalazzo** [comment]
Hi @darosior, I think that @lvaccaro pushed an update on this problem yesterday with this PR #40 

Do you are running the last version on master? sorry about the stupid question :smile:

**Comment by darosior** [comment]
That's absolutely not a stupid question! I think i updated some days ago so I missed that. Master moves fast nowadays ! :D

Closing this.
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by vincenzopalazzo** [comment]
Oh cool. I'm pretty sure that the UI now works. let me know :)

**Comment by darosior** [comment]
It does! Thanks, closing now.
