### ISSUE TITLE
Cannot scan URI QRs anymore

### ISSUE THREAD

**Issue by darosior** [lvaccaro/lamp#44]
I cannot scan QRcodes of the form `lightning:bolt11` anymore. I'm pretty sure i could about a month ago. I get a "could not parse destination address" error.

**Comment by vincenzopalazzo** [comment]
I think this is my fault, Maybe I jumped somethings on parse option.

I will check, sorry about that

**Comment by vincenzopalazzo** [comment]
@darosior my solution to this bug now is on master https://github.com/lvaccaro/lamp/pull/45. I hope this fix your bug :smile:

**Comment by vincenzopalazzo** [comment]
Marked as resolved :-)
