### ISSUE TITLE
Crash during startup (w/ autostart)

### ISSUE THREAD

**Issue by darosior** [lvaccaro/lamp#54]
When launching lamp, `lightningd` is launched automatically (great!). However, if i try to access the settings or the log during startup the app will crash. This does not happen with autostart disabled.

**Comment by vincenzopalazzo** [comment]
Hi @darosior, I reproduced this bug right now! Sorry about that! I will investigate on this

**Comment by vincenzopalazzo** [comment]
This should be fixed in the actual master. Thanks @darosior

**Comment by darosior** [comment]
Yep, fixed, thanks!

**Comment by vincenzopalazzo** [comment]
Fantastic @darosior :-)
