### ISSUE TITLE
UI: "balance updated" notification at startup

### ISSUE THREAD

**Issue by darosior** [lvaccaro/lamp#60]
While there were no update to my balance.

**Comment by darosior** [comment]
And each time i get back to the app actually

**Comment by vincenzopalazzo** [comment]
Hello @darosior, Baybe I made the same mistake inside the [notifier](https://github.com/lvaccaro/lamp/blob/master/app/src/main/java/com/lvaccaro/lamp/handlers/NewChannelPayment.kt), I will look inside. thanks :-)
