### ISSUE TITLE
UI: Input fields stay on screen after channel is open

### ISSUE THREAD

**Issue by jsarenik** [lvaccaro/lamp#66]
1. Scan QR code of the other node you want to connect to (containing `nodeid@address`)
2. Fund a channel
3. See the input fields stay on screen

I think the input fields should disappear after FUND CHANNEL button is pressed and the screen should return to the main screen.

**Comment by vincenzopalazzo** [comment]
Thanks for finding this UI bug.

A solution is proposed with the following PR https://github.com/lvaccaro/lamp/pull/62
