### ISSUE TITLE
Gossip sync

### ISSUE THREAD

**Issue by darosior** [lvaccaro/lamp#7]
I did not have time to really test Lamp yet (will do soon tho), but wanted to know if you already tried to sync gossip on mainnet and how it went.

If it's not feasible, we could use a nice hack to outsource the `getroute` (which will be called by `pay` itself) by using the `rpc_command` hook.

**Comment by lvaccaro** [comment]
Hi, I rebuild cross-compiled binaries with updated esplora plugin https://github.com/lvaccaro/lightning_ndk/releases/tag/release_clightning_0.8.1_1dc281c .
Think to test and profile soon on mainnet.

**Comment by darosior** [comment]
Nice to hear ! Think I'll do too asap :-)

**Comment by darosior** [comment]
Btw we're about to tag 0.8.2

**Comment by lvaccaro** [comment]
Network traffic from a new installation from 16.30 (626280) to 23.00 (626322).
Total traffic = 182 MB

1. Install the app
download binaries for aarch from https://github.com/lvaccaro/lightning_ndk/releases/tag/release_clightning_0.8.1_1dc281c
size 12.4 MB

2. Start node at 17.00 (block 626280) and fetch blocks size from (626280 - 100)
Total size of blocks 152.720058MB = from 626180 to current tip 626322

3. Gossiping:
182 MB - binaries - blocks = 16.9 MB

The screen shows the network traffic trend.
![photo_2020-04-16_23-22-26](https://user-images.githubusercontent.com/11627784/79508099-2de9a700-8039-11ea-95a6-3120bec7c20a.jpg)

**Comment by darosior** [comment]
Closing this, been a long way since ! :)
